dist: trusty
sudo: true

git:
  depth: false

language: csharp
mono: none
dotnet: 2.1.400

install:
# Install libimobiledevice from the Quamotion PPA
- sudo add-apt-repository -y ppa:quamotion/ppa
- sudo apt-get update
- sudo apt-get install -y libimobiledevice-dev libideviceactivation

- mkdir ext
- wget -nc https://qmcdn.blob.core.windows.net/imobiledevice/usbmuxd-osx-x64-1.1.0-113.tar.gz -O ext/usbmuxd-osx-x64-1.1.0-113.tar.gz
- wget -nc https://qmcdn.blob.core.windows.net/imobiledevice/usbmuxd-linux-x64-1.1.0-113.tar.gz -O ext/usbmuxd-linux-x64-1.1.0-113.tar.gz
- wget -nc https://qmcdn.blob.core.windows.net/imobiledevice/libimobiledevice-osx-x64-1.2.1-146.tar.gz -O ext/libimobiledevice-osx-x64-1.2.1-146.tar.gz
- wget -nc https://qmcdn.blob.core.windows.net/imobiledevice/libimobiledevice-linux-x64-1.2.1-146.tar.gz -O ext/libimobiledevice-linux-x64-1.2.1-146.tar.gz
- tar -xvzf ext/usbmuxd-osx-x64-1.1.0-113.tar.gz -C ext
- tar -xvzf ext/usbmuxd-linux-x64-1.1.0-113.tar.gz -C ext
- tar -xvzf ext/libimobiledevice-osx-x64-1.2.1-146.tar.gz -C ext
- tar -xvzf ext/libimobiledevice-linux-x64-1.2.1-146.tar.gz -C ext
- dotnet restore iMobileDevice-net/iMobileDevice-net.csproj

script:
- dotnet build -c Release iMobileDevice-net/iMobileDevice-net.csproj
- dotnet pack -c Release iMobileDevice-net/iMobileDevice-net.csproj
- dotnet test iMobileDevice.Generator.Tests/iMobileDevice.Generator.Tests.csproj
- dotnet test iMobileDevice.Tests/iMobileDevice.Tests.csproj