variables:
  imobiledevicenetBuild: 190
  imobiledevicenetPipeline: 1

jobs:
- job: deploy
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: $(imobiledevicenetPipeline)
      buildVersionToDownload: 'specific'
      buildId: $(imobiledevicenetBuild)
      downloadType: 'single'
      artifactName: 'imobiledevice-net'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download imobiledevice-net artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: $(imobiledevicenetPipeline)
      buildVersionToDownload: 'specific'
      buildId: $(imobiledevicenetBuild)
      downloadType: 'single'
      artifactName: 'binaries'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download binary artifacts'
  - script: |
      wget https://github.com/buildkite/github-release/releases/download/v1.0/github-release-linux-amd64 -O github-release
      chmod +x github-release

      sudo apt-get install -y libxml2-utils

      unzip $SYSTEM_ARTIFACTSDIRECTORY/imobiledevice-net/iMobileDevice-net.*.nupkg

      libplist_commit=`cat libplist.gitinfo/gitinfo | tail -n 1`
      libusbmuxd_commit=`cat libusbmuxd.gitinfo/gitinfo | tail -n 1`
      libimobiledevice_commit=`cat libimobiledevice.gitinfo/gitinfo | tail -n 1`
      usbmuxd_commit=`cat usbmuxd.gitinfo/gitinfo | tail -n 1`
      libideviceactivation_commit=`cat libideviceactivation.gitinfo/gitinfo | tail -n 1`
      imobiledevice_net_commit=$BUILD_SOURCEVERSION
      version_number=`xmllint --xpath 'Project/PropertyGroup/MobileDeviceDotNetNuGetVersion/text()' $SYSTEM_ARTIFACTSDIRECTORY/imobiledevice-net/Directory.Build.props`

      echo Releasing $version_number

      echo ./github-release "v$version_number" --commit "$libplist_commit" --github-repository "libplist-win32/libusbmuxd"
      ./github-release "v$version_number" --commit "$libplist_commit" --github-repository "libplist-win32/libusbmuxd"
      ./github-release "v$version_number" --commit "$libusbmuxd_commit" --github-repository "libimobiledevice-win32/libusbmuxd"
      ./github-release "v$version_number" --commit "$libimobiledevice_commit" --github-repository "libimobiledevice-win32/libimobiledevice"
      ./github-release "v$version_number" --commit "$usbmuxd_commit" --github-repository "libimobiledevice-win32/usbmuxd"
      ./github-release "v$version_number" --commit "$libideviceactivation_commit" --github-repository "libimobiledevice-win32/libideviceactivation"
      ./github-release "v$version_number" $SYSTEM_ARTIFACTSDIRECTORY/imobiledevice-net/iMobileDevice-net.*.nupkg binaries/*.zip --commit "$imobiledevice_net_commit" --github-repository "libimobiledevice-win32/imobiledevice-net_commit"
    displayName: Tag GitHub releases

# TODO: Publish NuGet package
# TODO: Publish usbmuxd Docker container