variables:
  imobiledevicenetBuild: 190
  imobiledevicenetPipeline: 1

jobs:
- job: deploy
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: $(imobiledevicenetPipeline)
      buildVersionToDownload: 'specific'
      buildId: $(imobiledevicenetBuild)
      downloadType: 'single'
      artifactName: 'imobiledevice-net'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download imobiledevice-net artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: $(imobiledevicenetPipeline)
      buildVersionToDownload: 'specific'
      buildId: $(imobiledevicenetBuild)
      downloadType: 'single'
      artifactName: 'binaries'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download binary artifacts'
  - script: |
      wget https://github.com/buildkite/github-release/releases/download/v1.0/github-release-linux-amd64 -O github-release
      chmod +x github-release
      unzip $SYSTEM_ARTIFACTSDIRECTORY/iMobileDevice-net.*.nupkg

    displayName: Tag GitHub releases
